site_name: 'Tech Blog'
site_url: https://yogesh1314.github.io
site_description: 'Personal Tech Wiki'

use_directory_urls: true

extra_css:
  - stylesheets/extra.css
  - stylesheets/prism.css # DO NOT ALTER 

extra_javascript:
  - scripts/prism.js
  - scripts/jquery-3.6.3.min.js # jQuery for scripts/qsearch.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yogesh1314
      name: Yogesh Rana on github
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/yogesh1314
      name: Yogesh Rana on linkedin

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
theme:
  name: material
  language: en
  logo: static/YR.svg
  favicon: static/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - navigation.top
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: 
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: material/lightbulb
        name: Switch to light mode


nav:
  - qkdb:
    - Index: qkdb/index.md
    - Atom-lists:
      - Basic Operations: qkdb/atom-lists/basic_operations.md
      - Atoms: qkdb/atom-lists/atom.md
      - Lists: qkdb/atom-lists/introduction_to_lists.md
      - List Operations: qkdb/atom-lists/list_operations.md
      - Hints and Tricks: qkdb/atom-lists/hints_and_tricks.md
    - Dictionary:
      - Dictionaries: qkdb/dict_table_func/1_dictionaries.md
      - Operation on Dictionaries: qkdb/dict_table_func/2_operations_on_dictionaries.md
    - Tables: qkdb/dict_table_func/3_tables.md
    - Functions: qkdb/dict_table_func/4_functions.md
    - Execution Control: qkdb/dict_table_func/5_execution_control.md
    - Scripts: qkdb/dict_table_func/6_scripts.md
    - Debugging: qkdb/dict_table_func/7_debugging.md
    - Q-SQL:
      - Select: qkdb/qsql/1_using_select_statements.md
      - Where: qkdb/qsql/2_where_clause.md
      - By: qkdb/qsql/3_by_clause.md
      - Functional Form: qkdb/qsql/4_functional_form.md
    - Keywords: qkdb/keywords-joins-adverbs-attributes/1_keywords.md
    - Joins:
      - Intro: qkdb/keywords-joins-adverbs-attributes/2_joins.md
      - Asof-Windows: qkdb/keywords-joins-adverbs-attributes/3_asof_window_joins.md
    - Adverbs: qkdb/keywords-joins-adverbs-attributes/4_adverbs.md
    - Attributes: qkdb/keywords-joins-adverbs-attributes/5_attributes.md
    - Index Amend: qkdb/keywords-joins-adverbs-attributes/6_index_amend_apply.md
    - IPC:
      - Connecting: qkdb/ipc-web-access/ipc_connecting.md
      - Send Receive: qkdb/ipc-web-access/ipc-sending-receiving.md 
      - Web Browser: qkdb/ipc-web-access/kdb-via-web-browser.md 
    - File I/O:
      - On disk tables: qkdb/fileio/on-disk-tables.md
      - Load save files: qkdb/fileio/load-save-files.md
    - Data Analysis:
      - Rack Align Pivot: qkdb/data-analysis/rack-align-pivot.md
      - Compare Profile: qkdb/data-analysis/compare-profile.md
      - Trade Analysis: qkdb/data-analysis/trade-analysis.md
      - Map Reduce Parallelization: qkdb/data-analysis/map-reduce-parallel.md
  - Advent-of-Code:
    - Y2023: aoc/23/index.md
